name: npm Package Deprecate

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'The version of the package to deprecate (e.g. 2.0.1, 0.x, 1.0.x, 0.1.0-alpha.x)'
        required: true

jobs:
  deprecate-npm:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
      - run: npm deprecate @blwat/utils@${{ github.event.inputs.package_version }} "Version ${{ github.event.inputs.package_version }} is no longer supported."
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
