name: npm and GitHub Package Publish

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The tag of the release being published (e.g. alpha, beta, next, latest)'
        required: true
        default: 'alpha'

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run lint:all
      - run: npm run build
      - run: npm test

  publish-npm:
    permissions:
      id-token: write
      contents: read
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --tag ${{ github.event.inputs.release_tag }}

  publish-github:
    permissions:
      contents: read
      packages: write
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24.x'
          registry-url: https://npm.pkg.github.com
          scope: '@blwatkins'
      - run: npm ci
      - run: npm publish --tag ${{ github.event.inputs.release_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
